version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.owasp:dependency-check-maven
    versions:
    - 6.1.0
    - 6.1.3
    - 6.1.4
  - dependency-name: com.sun.xml.ws:jaxws-rt
    versions:
    - 3.0.0
  - dependency-name: org.glassfish.jaxb:jaxb-xjc
    versions:
    - 3.0.0
  - dependency-name: org.glassfish.jaxb:jaxb-runtime
    versions:
    - 3.0.0
  - dependency-name: org.apache.derby:derbyclient
    versions:
    - 10.15.2.0
  - dependency-name: org.apache.derby:derby
    versions:
    - 10.15.2.0
