language: java

jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "warpsource"
    token:
      secure: vpr5d5abAvWDE7bq0l59vIqJ3lYow70vRT9LutF26z486NkmhHccfTjz/4ztjv4u924GjnH6BSDSsNdMkEmBP1CqVVsHGOnShFNxgGb+o9KttlHzphWX8F9HgwEgSjOwYdeZ3QNxbiYzZMJoaffO0EGAsts2F4lzrJVZALbiTb4oGC76fKlpha2tRRVVYJCGZx0nrfX6ItHbgVdZc/8PooL6q3SZ8u7VzHgxXZyaONXXCKsfkCl4Q0m+BC7vubWjr3KhV7jba+camrsmHE7UPU9QQVdmMCXbHD77nSlb8ZRfttK+nsWFfgdsNb+hyfkoLflvxAqUVXQWd5gc0poRsuj6H1hIx3o7294V0wges1HFAMdx96PqhB9vqyQ5BfZmGVmDakVEelchLhabXdzq2Uglg+A0SdVYMI9OGSSfjm6/iau9xqB1IcsQnt/XCRbj2nb+8gpv8Ddh/LyqNDDyX2hYrVH+H3Y6JT6Cb+fjDqSMlCsp3fFczhTiT74melnkUWE2Mf6ntDBfq5yAAAy+vjBivMGcokKeWiPOhiT4MOFLV43xEr038qPPU5EnBSGMYxVmDTQn1nzNZyU3i4EViiHBIArrbTBT2ZNQ7LEPD0D3778g9qTZyY0HwkI7oDWL4CmW1ZQ0/4AYzY42umkJM4/BQfX3Q2Oks76auCP+PCo=

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=WarpSource_as4-mail