name: DockerImageBuild
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build artefacts
        run: mvn -B clean verify
      - name: Build docker image
        # do not use docker/build-push-action@v2 because it cleans the repo
        # and did not find the property to disable that
        run: docker build -f ./docker/Dockerfile -t warpsource/as4mail-dev:latest .
      - name: Push docker image
        run: docker push warpsource/as4mail-dev:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}